"""
One-page PDF decision memo (plan Sec 9: "Export decision memo" button).
Pure fpdf2, no external template - a plain, readable summary of one
plan's cost/compliance breakdown, suitable for handing to a non-technical
stakeholder or attaching to an email.
"""
from __future__ import annotations
from fpdf import FPDF
from fpdf.enums import XPos, YPos


def build_memo_pdf(run_id: str, plan_id: str, ledger: dict) -> bytes:
    pdf = FPDF(format="A4")
    pdf.add_page()
    pdf.set_margin(20)

    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, "Q-FleetFlow - Fleet Plan Decision Memo", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Run {run_id}  /  Plan {plan_id}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(6)

    def section(title: str):
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(20, 20, 20)
        pdf.cell(0, 9, title, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_draw_color(180, 180, 180)
        pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 170, pdf.get_y())
        pdf.ln(3)

    def row(label: str, value: str, note: str | None = None):
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(40, 40, 40)
        pdf.cell(90, 7, label)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 7, value, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        if note:
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(140, 140, 140)
            pdf.cell(0, 5, note, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    section("Cost breakdown")
    row("Fuel cost", f"${ledger['fuel_cost_usd']:,.2f}")
    row("EU ETS cost", f"${ledger['ets_cost_usd']:,.2f}", "assumption-based EUA price - see factors.yaml")
    row("Demand penalty", f"${ledger['demand_penalty_usd']:,.2f}")
    total = ledger["fuel_cost_usd"] + ledger["ets_cost_usd"] + ledger["demand_penalty_usd"]
    pdf.ln(2)
    row("Total J1 cost", f"${total:,.2f}")
    pdf.ln(6)

    section("Regulatory compliance")
    compliant = ledger["fueleu_compliant"]
    status = "COMPLIANT" if compliant else "NON-COMPLIANT"
    row("FuelEU Maritime", status)
    row("Intensity vs. limit", f"{ledger['fueleu_intensity']:.2f} vs {ledger['fueleu_limit']:.2f} gCO2e/MJ")
    if not compliant:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(180, 60, 40)
        pdf.multi_cell(0, 5, "This plan exceeds the FuelEU Maritime intensity limit for the "
                             "target year and would require a pooling credit or a fuel-mix "
                             "change before use.")
    pdf.ln(4)

    section("Operational summary")
    row("Total CO2 (tank-to-wake)", f"{ledger['total_co2_ttw_t']:.1f} t")
    row("Schedule risk", f"{ledger['risk_hours']:.1f} hours over window")
    row("Legs in plan", f"{ledger['n_legs']}")
    pdf.ln(10)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 140, 140)
    pdf.multi_cell(
        0, 5,
        "Generated by Q-FleetFlow. All fuel and carbon prices are scenario assumptions, "
        "not live market data - see configs/factors.yaml and configs/scenario.yaml for "
        "sourcing. Prediction engine trained on synthetic data pending real fleet data "
        "integration."
    )

    return bytes(pdf.output())
